package Daje::Database::Model::CompaniesUsers;
use Mojo::Base 'Daje::Database::Model::Super::CompaniesUsers', -base, -signatures;

# Autogenerated class Sun Feb  9 13:11:20 2025
# This class is generated once. Any over rides or special methods should be put here




