package Daje::Database::View::VCompaniesUsers;
use Mojo::Base 'Daje::Database::View::Super::VCompaniesUsers', -base, -signatures;

# Autogenerated class Sun Feb  9 13:11:26 2025
# This class is generated once. Any over rides or special methods should be put here




