package Daje::Database::View::VUsersInCompany;
use Mojo::Base 'Daje::Database::View::Super::VUsersInCompany', -base, -signatures;

# Autogenerated class Sun Feb  9 13:11:28 2025
# This class is generated once. Any over rides or special methods should be put here




