package Daje::Database::View::VUsersInCompany;
use Mojo::Base 'Daje::Database::View::Super::VUsersInCompany', -base, -signatures;

# Autogenerated class Sat Mar  1 11:04:41 2025
# This class is generated once. Any over rides or special methods should be put here



1;
